[project]
name = "rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bs4>=0.0.2",
    "chromadb>=0.6.0",
    "click>=8.1.8",
    "mypy>=1.14.1",
    "openai>=1.58.1",
    "ruff>=0.8.5",
]
